# generated using the following command:
# for domain in domains/tfd-benchmarks/*; do if [[ -f "$domain/domain.pddl" ]]; then ls $domain | grep '^p' | grep -v 'dot\|txt' | sed -e "s@\(.*\)@.\/produce_graph.bash $domain domain.pddl \1@g"; fi; done > run_generation_1.bash
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p01.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p02.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p03.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p04.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p05.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p06.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p07.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p08.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p09.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p10.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p11.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p12.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p13.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p14.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p15.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p16.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p17.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p18.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p19.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p20.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p21.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p22.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p23.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p24.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p25.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p26.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p27.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p28.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p29.pddl
./produce_graph.bash domains/tfd-benchmarks/crewplanning-strips domain.pddl p30.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p01.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p02.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p03.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p04.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p05.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p06.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p07.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p08.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p09.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p10.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p11.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p12.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p13.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p14.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p15.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p16.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p17.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p18.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p19.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p20.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p21.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p22.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p23.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p24.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p25.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p26.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p27.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p28.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p29.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-numeric domain.pddl p30.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p01.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p02.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p03.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p04.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p05.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p06.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p07.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p08.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p09.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p10.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p11.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p12.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p13.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p14.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p15.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p16.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p17.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p18.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p19.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p20.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p21.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p22.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p23.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p24.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p25.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p26.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p27.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p28.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p29.pddl
./produce_graph.bash domains/tfd-benchmarks/elevators-strips domain.pddl p30.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p01.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p02.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p03.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p04.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p05.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p06.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p07.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p08.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p09.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p10.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p11.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p12.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p13.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p14.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p15.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p16.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p17.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p18.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p19.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p20.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p21.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p22.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p23.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p24.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p25.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p26.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p27.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p28.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p29.pddl
./produce_graph.bash domains/tfd-benchmarks/modeltrain-numeric domain.pddl p30.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p01.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p02.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p03.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p04.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p05.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p06.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p07.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p08.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p09.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p10.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p11.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p12.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p13.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p14.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p15.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p16.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p17.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p18.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p19.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p20.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p21.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p22.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p23.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p24.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p25.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p26.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p27.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p28.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p29.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-adl domain.pddl p30.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p01.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p02.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p03.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p04.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p05.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p06.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p07.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p08.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p09.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p10.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p11.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p12.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p13.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p14.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p15.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p16.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p17.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p18.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p19.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p20.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p21.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p22.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p23.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p24.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p25.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p26.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p27.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p28.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p29.pddl
./produce_graph.bash domains/tfd-benchmarks/openstacks-numericadl domain.pddl p30.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p01.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p02.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p03.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p04.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p05.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p06.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p07.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p08.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p09.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p10.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p11.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p12.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p13.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p14.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p15.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p16.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p17.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p18.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p19.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p20.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p21.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p22.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p23.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p24.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p25.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p26.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p27.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p28.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p29.pddl
./produce_graph.bash domains/tfd-benchmarks/pegsol-strips domain.pddl p30.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p01.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p02.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p03.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p04.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p05.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p06.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p07.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p08.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p09.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p10.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p11.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p12.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p13.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p14.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p15.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p16.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p17.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p18.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p19.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p20.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p21.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p22.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p23.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p24.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p25.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p26.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p27.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p28.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p29.pddl
./produce_graph.bash domains/tfd-benchmarks/sokoban-strips domain.pddl p30.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p01.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p02.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p03.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p04.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p05.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p06.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p07.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p08.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p09.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p10.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p11.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p12.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p13.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p14.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p15.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p16.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p17.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p18.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p19.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p20.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p21.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p22.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p23.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p24.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p25.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p26.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p27.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p28.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p29.pddl
./produce_graph.bash domains/tfd-benchmarks/transport-numeric domain.pddl p30.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p01.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p02.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p03.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p04.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p05.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p06.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p07.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p08.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p09.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p10.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p11.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p12.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p13.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p14.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p15.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p16.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p17.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p18.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p19.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p20.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p21.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p22.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p23.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p24.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p25.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p26.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p27.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p28.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p29.pddl
./produce_graph.bash domains/tfd-benchmarks/woodworking-numeric domain.pddl p30.pddl
